#!/usr/bin/env python3
"""
scripts/generate_compliance_pdf.py
Generates a highly professional, auditor-ready PDF report for SOC 2 Compliance.
Includes Infrastructure Footprint and HR Governance metrics.
"""

import argparse
import json
import datetime
import os
from pathlib import Path

try:
    from fpdf import FPDF, XPos, YPos
except ImportError:
    print("pip install fpdf2 required")
    import sys
    sys.exit(1)

class PDF(FPDF):
    def header(self):
        if self.page_no() == 1:
            return # No header on cover page
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, "CONFIDENTIAL - Automated SOC 2 Compliance Report", align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.line(10, 20, 200, 20)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Attest Automated Compliance Engine", align="C")

def sanitize(text):
    if not isinstance(text, str):
        return str(text)
    return text.replace("—", "-").replace("✅", "").replace("❌", "").replace("⚠️", "").encode("latin-1", "replace").decode("latin-1")

def create_pdf(summary_data: dict, output_path: str):
    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # ─── COVER PAGE ─────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(33, 37, 41)
    pdf.ln(50)
    pdf.cell(0, 15, "SOC 2 Type II Readiness Report", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, "Automated Evidence Collection & Validation", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.ln(30)
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 8, f"Date Generated: {summary_data.get('generated_at', 'Unknown')}", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    status = summary_data.get("overall_status", "UNKNOWN")
    pdf.set_font("Helvetica", "B", 14)
    pdf.ln(10)
    pdf.cell(0, 10, f"Overall Status: {status}", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.ln(40)
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 10, "Confidential & Proprietary", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    # ─── EXECUTIVE SUMMARY ──────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(33, 37, 41)
    pdf.cell(0, 10, "Executive Summary", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(5)
    
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(50, 8, "Total Controls Checked:")
    pdf.cell(0, 8, str(summary_data.get("total_controls_checked", 0)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.cell(50, 8, "Passed:")
    pdf.set_text_color(0, 128, 0)
    pdf.cell(0, 8, str(summary_data.get("pass_count", 0)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(33, 37, 41)
    
    pdf.cell(50, 8, "Failed:")
    pdf.set_text_color(200, 0, 0)
    pdf.cell(0, 8, str(summary_data.get("fail_count", 0)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(33, 37, 41)
    
    pdf.cell(50, 8, "Warnings:")
    pdf.set_text_color(200, 100, 0)
    pdf.cell(0, 8, str(summary_data.get("warn_count", 0)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(33, 37, 41)
    
    score = summary_data.get("compliance_score_percent", 0.0)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(50, 8, "Compliance Score:")
    if score >= 90: pdf.set_text_color(0, 128, 0)
    else: pdf.set_text_color(200, 0, 0)
    pdf.cell(0, 8, f"{score}%", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(33, 37, 41)
    pdf.ln(10)
    
    # ─── INFRASTRUCTURE SUMMARY ─────────────────────────────────────────────────
    infra = summary_data.get("infrastructure_summary", {})
    if infra:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "AWS Infrastructure Footprint (CC6, CC7)", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(60, 8, "Active IAM Users:")
        pdf.cell(0, 8, str(infra.get("iam_users", 0)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.cell(60, 8, "VPC Boundaries:")
        pdf.cell(0, 8, str(infra.get("vpcs", 0)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.cell(60, 8, "Subnets:")
        pdf.cell(0, 8, str(infra.get("subnets", 0)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.cell(60, 8, "EC2 Instances Active:")
        pdf.cell(0, 8, str(infra.get("ec2_instances", 0)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.cell(60, 8, "RDS Databases Active:")
        pdf.cell(0, 8, str(infra.get("rds_instances", 0)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(10)

    # ─── HR & GOVERNANCE SUMMARY ────────────────────────────────────────────────
    hr = summary_data.get("hr_summary", {})
    if hr:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "HR & Governance Footprint (CC1, CC2)", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(60, 8, "Active Headcount:")
        pdf.cell(0, 8, str(hr.get("active_employees", 0)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.cell(60, 8, "Background Checks Passed:")
        pdf.cell(0, 8, str(hr.get("bg_checks_passed", 0)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.cell(60, 8, "Training Completion Rate:")
        pdf.cell(0, 8, str(hr.get("training_completion_rate", "0%")), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.cell(60, 8, "Organizational Departments:")
        pdf.cell(0, 8, ", ".join(hr.get("departments", [])), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(10)

    # ─── CONTROL MATRIX ─────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Control Status Matrix", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(5)
    
    # Table Header
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(20, 8, "ID", border=1, fill=True)
    pdf.cell(90, 8, "Control Name", border=1, fill=True)
    pdf.cell(25, 8, "Status", border=1, fill=True)
    pdf.cell(55, 8, "Reason / Evidence", border=1, fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    # Table Rows
    pdf.set_font("Helvetica", "", 9)
    for ctrl in summary_data.get("controls_matrix", []):
        pdf.cell(20, 8, str(ctrl.get("id", "")), border=1)
        
        name = str(ctrl.get("name", ""))
        name = sanitize(name)
        name = name[:45] + "..." if len(name) > 45 else name
        pdf.cell(90, 8, name, border=1)
        
        status = sanitize(str(ctrl.get("status", "")))
        if status == "PASS": pdf.set_text_color(0, 128, 0)
        elif status == "FAIL": pdf.set_text_color(200, 0, 0)
        elif status == "WARN": pdf.set_text_color(200, 100, 0)
            
        pdf.cell(25, 8, status, border=1)
        pdf.set_text_color(33, 37, 41)
        
        reason = str(ctrl.get("reason", ""))
        reason = sanitize(reason)
        reason = reason[:30] + "..." if len(reason) > 30 else reason
        pdf.cell(55, 8, reason, border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
    pdf.output(output_path)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary", required=True)
    parser.add_argument("--output", default="soc2_compliance_report.pdf")
    parser.add_argument("--upload", action="store_true")
    parser.add_argument("--bucket")
    args = parser.parse_args()
    
    summary_path = Path(args.summary)
    if not summary_path.exists():
        print(f"Warning: {summary_path} not found. Generating fallback PDF.")
        data = {
            "generated_at": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            "overall_status": "CRITICAL (COLLECTION FAILED)",
        }
    else:
        data = json.loads(summary_path.read_text())
        
    create_pdf(data, args.output)
    print(f"[PDF Gen] Created {args.output}")
    
    if args.upload and args.bucket:
        import boto3
        s3 = boto3.client("s3")
        date_str = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
        key = f"attest-compliance-auditor/{date_str}/reports/{Path(args.output).name}"
        s3.upload_file(args.output, args.bucket, key,
                       ExtraArgs={"ContentType": "application/pdf"})
        print(f"[PDF Gen] Uploaded: s3://{args.bucket}/{key}")

if __name__ == "__main__":
    main()
